CREATE TABLE DEPT
(
    DEPTNO   NUMBER(2) PRIMARY KEY,
    DEPTNAME VARCHAR2(50) NOT NULL,
    DEPTADDR VARCHAR2(50)
);
COMMIT;

CREATE TABLE EMP
(
    EMPNO      NUMBER(4) PRIMARY KEY,
    EMPNAME    VARCHAR2(30) NOT NULL,
    BIRTHDATE  DATE,
    MANAGER_ID NUMBER(4) REFERENCES EMP (EMPNO)
);
COMMIT;

CREATE TABLE JOB
(
    JOBNO     NUMBER(4) PRIMARY KEY,
    JOBNAME   VARCHAR2(30) NOT NULL,
    MINSALARY NUMBER(6)
);
COMMIT;

CREATE TABLE CAREER
(
    JOBNO     NUMBER(4) REFERENCES JOB (JOBNO) NOT NULL,
    EMPNO     NUMBER(4) REFERENCES EMP (EMPNO) NOT NULL,
    DEPTNO    NUMBER(4) REFERENCES DEPT (DEPTNO),
    STARTDATE DATE                             NOT NULL,
    ENDDATE   DATE
);
COMMIT;

CREATE TABLE SALARY
(
    EMPNO    NUMBER(4) REFERENCES EMP (EMPNO),
    MONTH    NUMBER(2) CHECK (MONTH > 0 AND MONTH < 13),
    YEAR     NUMBER(4) CHECK (YEAR > 1987 AND YEAR < 2017),
    SALVALUE NUMBER(6)
);
COMMIT;
