version: '2'
services:
  database:
    image: store/oracle/database-enterprise:12.2.0.1
    container_name: oracle_db
    restart: always
    ports:
      - 1521:1521
      - 8080:8080
      - 5500:5500