DROP TABLE movie_actor CASCADE CONSTRAINTS PURGE;

DROP TABLE movie CASCADE CONSTRAINTS PURGE;

DROP TABLE actor CASCADE CONSTRAINTS PURGE;

DROP TABLE producer CASCADE CONSTRAINTS PURGE;

DROP SEQUENCE storage_seq;
DROP TRIGGER storage_id_trigger;
DROP TABLE storage CASCADE CONSTRAINTS PURGE;